### ISSUE TITLE
Setup for NUBS

### ISSUE THREAD

**Issue by SaphireVert** [SaphireVert/docker-minecraft#10]
It could be nice to add a feature that download and automatically install server for nubs

**Comment by ponsfrilus** [comment]
* [ ] Add a welcome header
* [ ] Check that all dependencies are installed, e.g. tmux, git, etc...
* [ ] Clone this repo and cd into dir (see https://unix.stackexchange.com/a/97922)
* [ ] cp `.env_sample` to `.env`
* [ ] ask question to change the `.env` file (wizard)
* [ ] finally, launch the server in a tmux process (see https://unix.stackexchange.com/questions/22682/how-to-launch-a-set-of-program-inside-tmux-or-gnome-terminal-within-a-script etc.)
